"""empty message

Revision ID: 173be8ada3df
Revises: bc971ed59101
Create Date: 2022-08-23 11:51:24.478584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '173be8ada3df'
down_revision = 'bc971ed59101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bike', 'precio',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=80),
               nullable=True)
    op.alter_column('bike', 'año',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=80),
               existing_nullable=True)
    op.alter_column('bike', 'modificaciones',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('bike', 'observaciones',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_constraint('bike_material_key', 'bike', type_='unique')
    op.drop_constraint('bike_modificaciones_key', 'bike', type_='unique')
    op.drop_constraint('bike_observaciones_key', 'bike', type_='unique')
    op.drop_constraint('bike_talla_key', 'bike', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('bike_talla_key', 'bike', ['talla'])
    op.create_unique_constraint('bike_observaciones_key', 'bike', ['observaciones'])
    op.create_unique_constraint('bike_modificaciones_key', 'bike', ['modificaciones'])
    op.create_unique_constraint('bike_material_key', 'bike', ['material'])
    op.alter_column('bike', 'observaciones',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('bike', 'modificaciones',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('bike', 'año',
               existing_type=sa.String(length=80),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('bike', 'precio',
               existing_type=sa.String(length=80),
               type_=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
