"""empty message

Revision ID: 29698ed31e6a
Revises: 6b4c50c71d3d
Create Date: 2022-08-19 09:37:39.815726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29698ed31e6a'
down_revision = '6b4c50c71d3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nombre', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('apellidos', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('telefono', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'user', ['telefono'])
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'telefono')
    op.drop_column('user', 'apellidos')
    op.drop_column('user', 'nombre')
    # ### end Alembic commands ###
