"""empty message

Revision ID: 6ec585afa959
Revises: 29698ed31e6a
Create Date: 2022-08-19 18:31:04.823128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ec585afa959'
down_revision = '29698ed31e6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=120), nullable=False),
    sa.Column('foto', sa.String(length=120), nullable=True),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('año', sa.Integer(), nullable=False),
    sa.Column('modificaciones', sa.String(length=200), nullable=False),
    sa.Column('talla', sa.String(length=80), nullable=False),
    sa.Column('material', sa.String(length=120), nullable=False),
    sa.Column('observaciones', sa.String(length=200), nullable=False),
    sa.Column('fechalimite', sa.Integer(), nullable=True),
    sa.Column('electrica', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material'),
    sa.UniqueConstraint('modificaciones'),
    sa.UniqueConstraint('observaciones'),
    sa.UniqueConstraint('talla')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bike')
    # ### end Alembic commands ###
