"""empty message

Revision ID: 90570edcbb16
Revises: ae1d8ee9b6f7
Create Date: 2022-09-02 15:46:55.689103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90570edcbb16'
down_revision = 'ae1d8ee9b6f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'estaciones', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'estaciones', type_='unique')
    # ### end Alembic commands ###
