"""empty message

<<<<<<<< HEAD:migrations/versions/ea8a8dd2b240_.py
Revision ID: ea8a8dd2b240
Revises: 
Create Date: 2022-08-26 16:58:59.693926
========
Revision ID: 988d4deafd01
Revises: 
Create Date: 2022-08-26 16:56:14.480473
>>>>>>>> footer2:migrations/versions/988d4deafd01_.py

"""
from alembic import op
import sqlalchemy as sa




revision = '988d4deafd01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=120), nullable=False),
    sa.Column('foto', sa.String(length=120), nullable=True),
    sa.Column('precio', sa.Integer(), nullable=True),
    sa.Column('año', sa.Integer(), nullable=True),
    sa.Column('modificaciones', sa.String(length=200), nullable=True),
    sa.Column('talla', sa.String(length=80), nullable=False),
    sa.Column('material', sa.String(length=120), nullable=False),
    sa.Column('observaciones', sa.String(length=200), nullable=True),
    sa.Column('fechalimite', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellidos', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefono')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('bike')
    # ### end Alembic commands ###
