"""empty message

Revision ID: d49e1f9d00e6
Revises: 2a308a192117
Create Date: 2022-09-05 14:14:00.958148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd49e1f9d00e6'
down_revision = '2a308a192117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'estaciones', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'estaciones', type_='unique')
    # ### end Alembic commands ###
