"""empty message

Revision ID: dee367d92c5e
Revises: b6f9d9bb4097
Create Date: 2022-09-05 09:22:12.776493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dee367d92c5e'
down_revision = 'b6f9d9bb4097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'estaciones', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'estaciones', type_='unique')
    # ### end Alembic commands ###
